# Generated by Django 5.2 on 2025-05-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoEliminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
    ]
