# Generated by Django 5.2 on 2025-06-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_boletacliente_boletaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fin_temporal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='inicio_temporal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rol_temporal',
            field=models.CharField(blank=True, choices=[('vendedor', 'Vendedor'), ('bodeguero', 'Bodeguero'), ('cajero', 'Cajero')], max_length=10, null=True),
        ),
    ]
