# Generated by Django 5.2 on 2025-07-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_producto_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_fin_oferta',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de fin de la oferta', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_inicio_oferta',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de inicio de la oferta', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento, por ejemplo: 15 para 15%', max_digits=5),
        ),
    ]
